# Generated by Django 4.0 on 2022-01-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ingles', models.CharField(max_length=50, verbose_name='nome_ingles')),
                ('nome_portugues', models.CharField(max_length=50, verbose_name='nome_portugues')),
                ('bandeira_url', models.CharField(max_length=40, verbose_name='bandeira_url')),
            ],
        ),
    ]
